Repository aws-samples/aws-serverless-developer-experience-workshop-java, pull requests merged in 2023-05, with the labels that each got.

#13 feat : githook and java17 with minor refactoring
  .github/workflows/build.yml
  pom.xml
  unicorn_contracts/ContractsFunction/pom.xml
  unicorn_contracts/ContractsFunction/src/main/java/contracts/CreateContractFunction.java
  unicorn_contracts/ContractsFunction/src/main/java/contracts/utils/ContractHelper.java
  unicorn_contracts/template.yaml
  unicorn_properties/PropertyFunctions/pom.xml
  unicorn_properties/template.yaml
  unicorn_web/PropertyFunctions/pom.xml
  unicorn_web/template.yaml
Labels: do-not-merge

#17 chore(ci): updating codeql configuration
  .github/workflows/codeql-analysis.yml
Labels: internal, pending-release

#19 chore: removing unnecessary deploy files
  unicorn_contracts/deploy
  unicorn_properties/deploy
Labels: do-not-merge, internal
